language: go
go_import_path: github.com/aws/amazon-ecs-init
sudo: false
go:
  - 1.12

matrix:
  include:
    - os: linux
      script:
        - make get-deps
        - make static-check
        - make test
        - make analyze-cover-profile
