# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox"

  ################
  #    UBUNTU/DEBIAN    #
  ################
  config.vm.define "ubuntu-18" do |box|
    box.vm.box = "bento/ubuntu-18.04"
  end
  config.vm.define "ubuntu-20" do |box|
    box.vm.box = "bento/ubuntu-20.04"
  end
  config.vm.define "debian-9" do |box|
    box.vm.box = "debian/contrib-stretch64"
  end
  config.vm.define "debian-10" do |box|
    box.vm.box = "debian/contrib-buster64"
  end

  ################
  #    CENTOS/FEDORA    #
  ################
  config.vm.define "fedora-33" do |box|
    box.vm.box = "generic/fedora33"
  end
  config.vm.define "fedora-32" do |box|
    box.vm.box = "generic/fedora32"
  end
  config.vm.define "centos-7" do |box|
    box.vm.box = "bento/centos-7"
  end
  config.vm.define "centos-8" do |box|
    box.vm.box = "bento/centos-8"
  end

  ################
  #    OTHER     #
  ################

  config.vm.define "suse" do |box|
    box.vm.box = "bento/opensuse-leap-15.2"
  end

  config.vm.define "rhel-8" do |box|
    box.vm.box = "generic/rhel8"
  end

  config.vm.define "al2" do |box|
    box.vm.box = "bento/amazonlinux-2"
  end

  config.vm.define "windows" do |box|
    box.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
    # box.vm.network "private_network", ip: "192.168.34.21"
    #box.vm.provider "vmware_fusion"
    #box.vm.provider "virtualbox"
  end

  config.vm.provider "virtualbox" do |vb|
   vb.customize ["modifyvm", :id, "--vram", "128"]
   vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
